### ISSUE TITLE
Not working properly on Android

### ISSUE THREAD

**Issue by thecoorum** [enesozturk/react-native-hold-menu#66]
**Describe the bug**
After opening the hold menu on Android it just freezes, no actions can be performed, and can't close the menu by tapping on the backdrop

**To Reproduce**
1. Activate the hold menu
2. Try to press on item (no result)
3. Try to close the overlay by tapping on the backdrop (no result)
4. Try to close the overlay by tapping on the hold menu item with the `closeOnTap` prop (no result)

**Expected behavior**
Either action is performed or the menu is closed on one of the possible actions

**Actual behavior**
Neither action performed nor overlay closed

**Screenshots**

**Package versions**
 - React: 17.0.1
 - React Native: 0.64.3
 - React Native Reanimated: 2.3.1
 - React Native Hold Menu: 0.1.3
 - Expo: 44.0.0

**Comment by dancixx** [comment]
I had the same issue, and it solved after I put the HoldMenuProvider as child into the GestureHandlerRootView.

```
<GestureHandlerRootView style={{flex: 1}}>
                            <HoldMenuProvider theme="light" paddingBottom={40}>
                              <Screen>
                                <Start authentication={authentication} />
                              </Screen>
                            </HoldMenuProvider>
</GestureHandlerRootView>
```

**Comment by enesozturk** [comment]
Hi @thecoorum, I got both issues and made some fixes with my latest PR (https://github.com/enesozturk/react-native-hold-menu/pull/73). Now they should work as expected. Also @dancixx's solution can be good because, on Android, I needed to use Pressable instead of GestureHandler because it wasn't working as expected, unlike the iOS. I'll give it a try, thanks!
